# Generated by Django 5.2.6 on 2025-10-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),  # <--- antes apuntaba a ('api', 'migrations')
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE notas_actividad DROP CONSTRAINT IF EXISTS uq_notas_actividad;"
        ),
        migrations.RemoveConstraint(
            model_name='notasactividad',
            name='pk_notas_actividad',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='id',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='id',
        ),
        migrations.RemoveField(
            model_name='indicadoresdelogro',
            name='id',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='id',
        ),
        migrations.RemoveField(
            model_name='periodoacademico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='raactividad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resultadodeaprendizaje',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tipoactividad',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='id',
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_actividad',
            field=models.BigAutoField(db_column='id_actividad', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='id_asignatura',
            field=models.BigAutoField(db_column='id_asignatura', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='docente',
            name='id_docente',
            field=models.BigAutoField(db_column='id_docente', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_estudiante',
            field=models.BigAutoField(db_column='id_estudiante', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='indicadoresdelogro',
            name='id_ind',
            field=models.BigAutoField(db_column='id_ind', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='matricula',
            name='id_matricula',
            field=models.BigAutoField(db_column='id_matricula', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='id_periodo',
            field=models.BigAutoField(db_column='id_periodo', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='programa',
            name='id_programa',
            field=models.BigAutoField(db_column='id_programa', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='raactividad',
            name='id_ra_actividad',
            field=models.BigAutoField(db_column='id_ra_actividad', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='resultadodeaprendizaje',
            name='id_ra',
            field=models.BigAutoField(db_column='id_ra', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tipoactividad',
            name='id_tipo_actividad',
            field=models.BigAutoField(db_column='id_tipo_actividad', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='id_tipo_documento',
            field=models.BigAutoField(db_column='id_tipo_documento', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notasactividad',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='notasactividad',
            constraint=models.UniqueConstraint(fields=('matricula', 'ra_actividad'), name='uq_notas_actividad'),
        ),
    ]
