# Generated by Django 5.2.6 on 2025-10-01 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porcentaje_actividad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_creacion', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('codigo_docente', models.CharField(max_length=50, unique=True)),
                ('contrasenia_docente', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('num_documento', models.CharField(max_length=50, unique=True)),
                ('num_telefono', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('codigo_estudiante', models.CharField(max_length=50, unique=True)),
                ('contrasena_estudiante', models.CharField(max_length=255)),
                ('num_documento', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('jornada', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_programa', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'programa',
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tipo_actividad',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_asignatura', models.CharField(max_length=50, unique=True)),
                ('grupo', models.CharField(blank=True, max_length=20, null=True)),
                ('docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.RESTRICT, to='api.docente')),
                ('programa', models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.RESTRICT, to='api.programa')),
            ],
            options={
                'db_table': 'asignatura',
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
            ],
            options={
                'db_table': 'periodo_academico',
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_finalizacion__gte', models.F('fecha_inicio'))), name='chk_periodo_fechas')],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.RESTRICT, to='api.asignatura')),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
                ('periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.RESTRICT, to='api.periodoacademico')),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
        migrations.CreateModel(
            name='RaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_ra_actividad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actividad', models.ForeignKey(db_column='id_actividad', on_delete=django.db.models.deletion.CASCADE, to='api.actividad')),
            ],
            options={
                'db_table': 'ra_actividad',
            },
        ),
        migrations.CreateModel(
            name='NotasActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_ra_actividad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retroalimentacion', models.TextField(blank=True, null=True)),
                ('matricula', models.ForeignKey(db_column='id_matricula', on_delete=django.db.models.deletion.CASCADE, to='api.matricula')),
                ('ra_actividad', models.ForeignKey(db_column='id_ra_actividad', on_delete=django.db.models.deletion.CASCADE, to='api.raactividad')),
            ],
            options={
                'db_table': 'notas_actividad',
            },
        ),
        migrations.CreateModel(
            name='ResultadoDeAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_ra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.CASCADE, to='api.asignatura')),
            ],
            options={
                'db_table': 'resultado_de_aprendizaje',
            },
        ),
        migrations.AddField(
            model_name='raactividad',
            name='ra',
            field=models.ForeignKey(db_column='id_ra', on_delete=django.db.models.deletion.CASCADE, to='api.resultadodeaprendizaje'),
        ),
        migrations.CreateModel(
            name='IndicadoresDeLogro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_ind', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ra', models.ForeignKey(db_column='id_ra', on_delete=django.db.models.deletion.CASCADE, to='api.resultadodeaprendizaje')),
            ],
            options={
                'db_table': 'indicadores_de_logro',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.ForeignKey(db_column='id_tipo_actividad', on_delete=django.db.models.deletion.RESTRICT, to='api.tipoactividad'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.ForeignKey(db_column='id_tipo_documento', on_delete=django.db.models.deletion.RESTRICT, to='api.tipodocumento'),
        ),
        migrations.AddField(
            model_name='docente',
            name='tipo_documento',
            field=models.ForeignKey(db_column='id_tipo_documento', on_delete=django.db.models.deletion.RESTRICT, to='api.tipodocumento'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.CheckConstraint(condition=models.Q(('nota_final__isnull', True), models.Q(('nota_final__gte', 0), ('nota_final__lte', 5)), _connector='OR'), name='chk_nota_final'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('estudiante', 'periodo', 'asignatura'), name='uq_matricula'),
        ),
        migrations.AddConstraint(
            model_name='notasactividad',
            constraint=models.UniqueConstraint(fields=('matricula', 'ra_actividad'), name='pk_notas_actividad'),
        ),
        migrations.AddConstraint(
            model_name='notasactividad',
            constraint=models.CheckConstraint(condition=models.Q(('nota_ra_actividad__isnull', True), models.Q(('nota_ra_actividad__gte', 0), ('nota_ra_actividad__lte', 5)), _connector='OR'), name='chk_nota_ra'),
        ),
        migrations.AddConstraint(
            model_name='resultadodeaprendizaje',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_ra__gte', 0), ('porcentaje_ra__lte', 100)), name='chk_ra_pct'),
        ),
        migrations.AddConstraint(
            model_name='raactividad',
            constraint=models.UniqueConstraint(fields=('actividad', 'ra'), name='uq_ra_act'),
        ),
        migrations.AddConstraint(
            model_name='raactividad',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_ra_actividad__gte', 0), ('porcentaje_ra_actividad__lte', 100)), name='chk_ra_act_pct'),
        ),
        migrations.AddConstraint(
            model_name='indicadoresdelogro',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_ind__gte', 0), ('porcentaje_ind__lte', 100)), name='chk_ind_pct'),
        ),
        migrations.AddConstraint(
            model_name='actividad',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_actividad__gte', 0), ('porcentaje_actividad__lte', 100)), name='chk_act_pct'),
        ),
        migrations.AddConstraint(
            model_name='actividad',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_cierre__isnull', True), ('fecha_cierre__gte', models.F('fecha_creacion')), _connector='OR'), name='chk_act_fechas'),
        ),
    ]
