# Generated by Django 5.2.6 on 2025-10-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_remove_notasactividad_pk_notas_actividad_and_more'),
        ('api', '0003_notasactividad_surrogate_pk'),
    ]

    operations = [
    ]
