# Generated by Django 5.2.6 on 2025-10-02 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20251001_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasactividad',
            name='indicador',
            field=models.ForeignKey(blank=True, db_column='id_ind', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.indicadoresdelogro'),
        ),
    ]
