# Generated by Django 5.2.6 on 2025-10-06 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notasactividad_indicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.BigAutoField(db_column='id_recurso', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='recursos/%Y/%m/%d')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.CASCADE, to='api.asignatura')),
            ],
            options={
                'db_table': 'recurso',
            },
        ),
    ]
