# Generated by Django 5.2.6 on 2025-10-21 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sync_notasactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaActividadIndicador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('indicador', models.ForeignKey(db_column='id_ind', on_delete=django.db.models.deletion.CASCADE, related_name='ra_actividades_rel', to='api.indicadoresdelogro')),
                ('ra_actividad', models.ForeignKey(db_column='id_ra_actividad', on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_rel', to='api.raactividad')),
            ],
            options={
                'db_table': 'ra_actividad_indicador',
                'constraints': [models.UniqueConstraint(fields=('ra_actividad', 'indicador'), name='uq_ra_actividad_indicador')],
            },
        ),
    ]
