# Generated by Django 5.2.6 on 2025-11-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_hash_coordinador_password'),
    ]

    operations = [
        migrations.RunSQL(
            sql=("ALTER TABLE actividad DROP CONSTRAINT IF EXISTS chk_act_pct;"),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
