# Generated by Django 5.2.6 on 2025-11-11 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_actividad_chk_act_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('matriculados', 'Matriculados'), ('docentes', 'Docentes'), ('asignaturas_ras', 'Asignaturas y RAs')], max_length=32)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('created_count', models.IntegerField(default=0)),
                ('existing_count', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'import_audit',
            },
        ),
        migrations.RunSQL(
            sql=("ALTER TABLE actividad DROP CONSTRAINT IF EXISTS chk_act_pct;"),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='importaudit',
            name='coordinador',
            field=models.ForeignKey(db_column='id_coordinador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coordinador'),
        ),
        migrations.AddIndex(
            model_name='importaudit',
            index=models.Index(fields=['kind', 'created_at'], name='idx_import_kind_created'),
        ),
    ]
