# Generated by Django 5.2.6 on 2025-11-11 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_importaudit_remove_actividad_chk_act_pct_and_more'),
    ]

    operations = [
    ]
