# Generated by Django 5.2.6 on 2025-11-18 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20251111_1714'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actividad',
            name='chk_act_pct',
        ),
    ]
