# Generated by Django 5.2.8 on 2025-11-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notasactividad',
            name='uq_notas_actividad',
        ),
        migrations.AddConstraint(
            model_name='notasactividad',
            constraint=models.UniqueConstraint(fields=('matricula', 'ra_actividad', 'indicador'), name='uq_notas_actividad_indicador'),
        ),
    ]
