# Generated by Django 5.2.6 on 2025-11-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_actividad_chk_act_pct'),
    ]

    operations = [
        migrations.RunSQL(
            sql=("ALTER TABLE actividad DROP CONSTRAINT IF EXISTS chk_act_pct;"),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
