# Generated by Django 5.2.6 on 2025-11-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_actividad_chk_act_pct'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actividad',
            name='chk_act_pct',
        ),
    ]
