# Generated by Django 5.2.8 on 2026-02-25 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_security_audit_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('es_importante', models.BooleanField(default=False, help_text='Marca si el anuncio es urgente/importante')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='api.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='api.docente')),
            ],
            options={
                'db_table': 'anuncio',
                'ordering': ['-fecha_publicacion'],
                'indexes': [
                    models.Index(fields=['asignatura', '-fecha_publicacion'], name='anuncio_asignat_502ac8_idx'),
                ],
            },
        ),
    ]
