# Generated by manual creation
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_anuncio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('grade', 'Calificación'), ('resource', 'Recurso'), ('deadline', 'Fecha límite'), ('message', 'Mensaje'), ('announcement', 'Anuncio')], db_index=True, default='message', max_length=20)),
                ('texto', models.TextField(help_text='Contenido de la notificación')),
                ('enlace', models.CharField(blank=True, help_text='URL opcional para redirigir', max_length=500, null=True)),
                ('leida', models.BooleanField(db_index=True, default=False, help_text='Si el estudiante ya leyó esta notificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, help_text='Fecha en que se marcó como leída', null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='api.estudiante')),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['estudiante', '-fecha_creacion'], name='notificacio_estudia_8a7e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['estudiante', 'leida'], name='notificacio_estudia_9c8f7a_idx'),
        ),
    ]
