# Generated by manual creation
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_notificacion'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS api_task CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='Task',
                ),
            ],
        ),
    ]
