# Generated by Django 5.2.8 on 2026-03-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_task_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importaudit',
            name='kind',
            field=models.CharField(choices=[('matriculados', 'Matriculados'), ('estudiantes', 'Estudiantes'), ('docentes', 'Docentes'), ('asignaturas_ras', 'Asignaturas y RAs')], max_length=32),
        ),
    ]
