# Generated by Django 5.2.12 on 2026-05-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_estudiante_activo'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE actividad DROP CONSTRAINT IF EXISTS chk_act_pct;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='notificacio_estudia_bbe226_idx',
            old_name='notificacio_estudia_8a7e8b_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='notificacio_estudia_25c8bb_idx',
            old_name='notificacio_estudia_9c8f7a_idx',
        ),
    ]
