# Generated by Django 5.2.12 on 2026-05-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_actividad_chk_act_pct_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='indicadoresdelogro',
            name='chk_ind_pct',
        ),
        migrations.RemoveField(
            model_name='indicadoresdelogro',
            name='porcentaje_ind',
        ),
    ]
