# Generated by Django 5.2.12 on 2026-05-11 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_porcentaje_ind_from_indicadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='programa',
            field=models.ForeignKey(blank=True, db_column='id_programa', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.programa'),
        ),
    ]
