# Generated by Django 5.2.12 on 2026-05-11 16:10

from django.db import migrations, models


def assign_numero_ra(apps, schema_editor):
    """Asigna números secuenciales (1, 2, 3...) a cada RA por asignatura"""
    ResultadoDeAprendizaje = apps.get_model('api', 'ResultadoDeAprendizaje')
    
    # Obtener todas las asignaturas y sus RAs
    asignaturas_dict = {}
    for ra in ResultadoDeAprendizaje.objects.all().order_by('asignatura_id', 'id_ra'):
        asig_id = ra.asignatura_id
        if asig_id not in asignaturas_dict:
            asignaturas_dict[asig_id] = []
        asignaturas_dict[asig_id].append(ra)
    
    # Actualizar cada RA con su número secuencial
    for asig_id, ras in asignaturas_dict.items():
        for idx, ra in enumerate(ras, start=1):
            ra.numero_ra = idx
            ra.save()


def reverse_numero_ra(apps, schema_editor):
    """Revierte a todos los RAs el número 1"""
    ResultadoDeAprendizaje = apps.get_model('api', 'ResultadoDeAprendizaje')
    ResultadoDeAprendizaje.objects.all().update(numero_ra=1)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_restore_tipo_actividad_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadodeaprendizaje',
            name='numero_ra',
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(assign_numero_ra, reverse_numero_ra),
        migrations.AddConstraint(
            model_name='resultadodeaprendizaje',
            constraint=models.UniqueConstraint(fields=('asignatura', 'numero_ra'), name='uq_ra_numero_por_asignatura'),
        ),
    ]

