# Generated by Copilot on 2026-05-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_normalize_tipo_documento_abbr"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="programa",
            field=models.ForeignKey(
                blank=True,
                db_column="id_programa",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="api.programa",
            ),
        ),
    ]
