# Generated by Django 5.2.13 on 2026-05-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_estudiante_programa'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "DO $$ BEGIN "
                "IF EXISTS (SELECT 1 FROM pg_class WHERE relname='api_actividad') THEN "
                "  ALTER TABLE api_actividad DROP CONSTRAINT IF EXISTS chk_act_pct; "
                "END IF; "
                "END $$;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
