services:
  - type: web
    name: ra-manager-backend
    env: python
    plan: starter
    branch: main
    root: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120
    envVars:
      - key: xj)4)m%!xkyuepq)coll=nd@rrldb9iqt+5^k3+w^#t)se%-sr
        fromDatabase: false
      - key: DEBUG
        fromDatabase: false
      - key: DATABASE_URL
        fromDatabase: false
      - key: FRONTEND_URL
        fromDatabase: false
      - key: CORS_ORIGINS
        fromDatabase: false
      - key: DB_CONN_MAX_AGE
        fromDatabase: false
