"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# Validar que SECRET_KEY esté configurada (especialmente en producción)
if not SECRET_KEY:
    raise ValueError(
        "La variable de entorno SECRET_KEY no está configurada. "
        "Por favor, copia .env.example a .env y genera una SECRET_KEY segura con: "
        "python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )

# En producción, validar que no sea la clave por defecto
if not DEBUG and SECRET_KEY.startswith('django-insecure'):
    raise ValueError(
        "⚠️ PELIGRO: Estás usando una SECRET_KEY insegura en producción. "
        "Genera una nueva con: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )

# Parse ALLOWED_HOSTS from environment variable (comma-separated)
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Security settings for production (only when DEBUG=False)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', str(not DEBUG)) == 'True'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', str(not DEBUG)) == 'True'

# Parse CORS origins from environment variable (comma-separated)
cors_origins = os.getenv('CORS_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173')
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins.split(',')]
CORS_ORIGIN_ALLOW_ALL = DEBUG  # Allow all in development, restrict in production

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

# Base URL del frontend para enlaces (recuperación de contraseña, etc.)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'ra_manager'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "corsheaders",
    "drf_spectacular",  # Documentación API con Swagger/OpenAPI
    "api.apps.ApiConfig",  # <-- registra tu app
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom middleware para manejo robusto de errores y logging
    'api.middleware.error_handler.RequestLoggingMiddleware',
    'api.middleware.error_handler.ErrorHandlerMiddleware',
    # Rate limiting middleware para registrar eventos de seguridad
    'api.middleware.ratelimit.RateLimitMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
            'level': 'ERROR',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# ==================== EMAIL CONFIGURATION ====================
# Para desarrollo: imprime los correos en la consola
# Para producción: configura SMTP en el archivo .env
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@univalle.local')

# Configuración para recuperación de contraseña con OTP
OTP_EXPIRY_MINUTES = int(os.getenv('OTP_EXPIRY_MINUTES', '5'))  # Tiempo de expiración del OTP en minutos

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = "/media/"
MEDIA_ROOT = Path(__file__).resolve().parent.parent / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    # Paginación habilitada para mejorar performance en listados grandes
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,  # 50 items por página por defecto
    
    # Autenticación basada en tokens bearer
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    
    # Por defecto, requiere autenticación (se puede sobrescribir por endpoint)
    "DEFAULT_PERMISSION_CLASSES": [],
    
    # Formato de respuesta
    # En desarrollo se habilita la Browsable API para facilitar pruebas manuales.
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        *(["rest_framework.renderers.BrowsableAPIRenderer"] if DEBUG else []),
    ],
    
    # Throttling global para prevenir abuso
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # En desarrollo: límites más altos por React Strict Mode
        "anon": "10000/hour" if DEBUG else "100/hour",
        "user": "10000/hour" if DEBUG else "1000/hour",
    },
    
    # Documentación API con drf-spectacular
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# Configuración de drf-spectacular para documentación API
SPECTACULAR_SETTINGS = {
    'TITLE': 'RA-Manager API',
    'DESCRIPTION': 'API REST para el sistema de gestión de Resultados de Aprendizaje (RA-Manager)',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Oculta warnings/errores de introspección del esquema para vistas APIView/@api_view.
    'DISABLE_ERRORS_AND_WARNINGS': True,
    
    # Información de contacto
    'CONTACT': {
        'name': 'Equipo RA-Manager',
        'email': 'soporte@ra-manager.com',
    },
    
    # Configuración de la UI
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    
    # Schemas
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api',
    
    # Autenticación
    'SECURITY': [],
    
    # Tags para agrupar endpoints
    'TAGS': [
        {'name': 'Autenticación', 'description': 'Login, logout, recuperación de contraseña'},
        {'name': 'Coordinador', 'description': 'Endpoints para coordinadores'},
        {'name': 'Docente', 'description': 'Endpoints para docentes'},
        {'name': 'Estudiante', 'description': 'Endpoints para estudiantes'},
        {'name': 'Asignaturas', 'description': 'Gestión de asignaturas'},
        {'name': 'Resultados de Aprendizaje', 'description': 'Gestión de RAs e indicadores'},
        {'name': 'Actividades', 'description': 'Gestión de actividades y calificaciones'},
        {'name': 'Catálogos', 'description': 'Tipos de documento, actividades, programas'},
        {'name': 'Perfil', 'description': 'Gestión de perfil de usuario'},
    ],
}
